Repository get6pm/6pm, pull requests merged in 2024-08, with the labels that each got.

#194 chore(mobile): set ios ascAppId
  apps/mobile/eas.json
Labels: eas-build-ios

#198 feat(mobile): clear all cache when user change
  apps/mobile/app/(app)/(tabs)/settings.tsx
  apps/mobile/app/_layout.tsx
  apps/mobile/lib/utils.ts
  apps/mobile/stores/budget/hooks.tsx
  apps/mobile/stores/budget/store.ts
  apps/mobile/stores/category/hooks.tsx
  apps/mobile/stores/category/store.ts
  apps/mobile/stores/store-provider.tsx
  apps/mobile/stores/transaction/hooks.tsx
  apps/mobile/stores/transaction/store.ts
  apps/mobile/stores/use-reset-all-stores.tsx
Labels: eas-build-ios

#199 chore(mobile): upgrade sentry version
  apps/mobile/package.json
  pnpm-lock.yaml
Labels: enhancement, frontend, eas-build-ios

#203 feat(mobile): setup eas update
  apps/mobile/app.json
  apps/mobile/eas.json
  apps/mobile/package.json
  pnpm-lock.yaml
Labels: enhancement, frontend

#210 fix(mobile): force load intl polyfills
  apps/mobile/index.js
Labels: enhancement, frontend

#214 fix(mobile): refactor expo setup to adapt expo-updates
  apps/mobile/app.json
  apps/mobile/app/_layout.tsx
  apps/mobile/index.js
  apps/mobile/package.json
Labels: bug, frontend

#221 feat(mobile): quick add new category from transaction form
  apps/mobile/components/transaction/select-account-field.tsx
  apps/mobile/components/transaction/select-category-field.tsx
Labels: enhancement, frontend

#222 feat(mobile): allow change currency in transaction form and correct total amount statistic with currency exchange
  apps/mobile/components/home/wallet-statistics.tsx
  apps/mobile/components/text-ticker/text-ticker.tsx
  apps/mobile/components/transaction/transaction-form.tsx
Labels: enhancement, frontend

#224 fix(mobile): fix header font to Inter
  apps/mobile/app/(app)/(tabs)/_layout.tsx
  apps/mobile/app/(app)/_layout.tsx
  apps/mobile/app/(aux)/_layout.tsx
  apps/mobile/app/_layout.tsx
  apps/mobile/components/budget/budget-statistic.tsx
  apps/mobile/components/common/amount-format.tsx
  apps/mobile/components/common/toast.tsx
  apps/mobile/components/numeric-pad/numeric-pad.tsx
  apps/mobile/components/text-ticker/text-ticker.tsx
  apps/mobile/components/transaction/transaction-form.tsx
Labels: enhancement, frontend

#225 feat(mobile): allow input negative wallet balance and float numbers
  apps/api/v1/services/budget.service.ts
  apps/mobile/app/(app)/wallet/[walletId].tsx
  apps/mobile/app/(app)/wallet/new-account.tsx
  apps/mobile/components/budget/budget-form.tsx
  apps/mobile/components/ui/collapsible.tsx
  apps/mobile/components/wallet/account-form.tsx
  apps/mobile/components/wallet/select-balance-state-field.tsx
  apps/mobile/package.json
  apps/mobile/queries/wallet.ts
  packages/validation/src/budget.zod.ts
  packages/validation/src/wallet.zod.ts
  pnpm-lock.yaml
Labels: enhancement, frontend

#227 fix(mobile): fix transform with key of translateY crashes
  apps/mobile/app/(app)/transaction/[transactionId].tsx
  apps/mobile/app/(app)/transaction/new-record.tsx
  apps/mobile/components/auth/auth-email.tsx
  apps/mobile/components/common/toolbar.tsx
  apps/mobile/components/form-fields/input-field.tsx
  apps/mobile/components/transaction/scanner.tsx
Labels: bug, enhancement

#228 feat(api): cascade budget users when delete budget
  apps/api/prisma/migrations/20240820081223_cascading_budget_users_on_budget_deleted/migration.sql
  apps/api/prisma/schema.prisma
Labels: enhancement, backend

#229 feat(mobile): update and delete budget
  apps/mobile/app/(app)/budget/[budgetId]/edit.tsx
  apps/mobile/app/(app)/budget/[budgetId]/index.tsx
  apps/mobile/components/budget/budget-item.tsx
  apps/mobile/components/budget/period-control.tsx
  apps/mobile/components/ui/input.tsx
  apps/mobile/components/ui/text.tsx
  apps/mobile/lib/date.tsx
  apps/mobile/stores/budget/hooks.tsx
  apps/mobile/stores/budget/store.ts
  apps/mobile/stores/transaction/hooks.tsx
Labels: enhancement, frontend

#230 feat(mobile): add onboard user budget screen
  apps/mobile/app/(app)/_layout.tsx
  apps/mobile/app/onboarding/_layout.tsx
  apps/mobile/app/onboarding/step-one.tsx
  apps/mobile/app/onboarding/step-two.tsx
  apps/mobile/components/budget/budget-item.tsx
  apps/mobile/components/common/amount-format.tsx
  apps/mobile/components/svg-assets/onboard-illustration.tsx
  apps/mobile/components/transaction/transaction-form.tsx
Labels: enhancement, frontend

#231 feat(mobile): add schedule input reminder notification
  apps/mobile/app/(app)/(tabs)/settings.tsx
  apps/mobile/app/(app)/_layout.tsx
  apps/mobile/app/_layout.tsx
  apps/mobile/app/onboarding/_layout.tsx
  apps/mobile/app/onboarding/step-three.tsx
  apps/mobile/app/onboarding/step-two.tsx
  apps/mobile/components/svg-assets/notification-illustration.tsx
  apps/mobile/hooks/use-schedule-notification.tsx
  apps/mobile/package.json
  apps/mobile/stores/user-settings/store.ts
  pnpm-lock.yaml
Labels: enhancement, frontend

#233 fix(mobile): lazy load transaction scanner
  apps/mobile/app/(app)/transaction/new-record.tsx
  apps/mobile/components/transaction/scanner.tsx
  apps/mobile/locales/en/messages.po
  apps/mobile/locales/en/messages.ts
  apps/mobile/locales/vi/messages.po
  apps/mobile/locales/vi/messages.ts
Labels: enhancement, frontend

#234 feat(mobile): add real privacy policy
  apps/mobile/app/(app)/(tabs)/settings.tsx
  apps/mobile/app/(auth)/login.tsx
  apps/mobile/app/(aux)/_layout.tsx
  apps/mobile/app/(aux)/privacy-policy.tsx
  apps/mobile/components/transaction/scanner.tsx
  apps/mobile/locales/en/messages.po
  apps/mobile/locales/en/messages.ts
  apps/mobile/locales/vi/messages.po
  apps/mobile/locales/vi/messages.ts
Labels: enhancement, frontend

#235 feat(mobile): add biometric local authentication
  apps/mobile/app.json
  apps/mobile/app/(app)/(tabs)/settings.tsx
  apps/mobile/app/(app)/_layout.tsx
  apps/mobile/components/auth/auth-local.tsx
  apps/mobile/components/setting/profile-card.tsx
  apps/mobile/components/setting/set-local-auth.tsx
  apps/mobile/hooks/use-local-auth.tsx
  apps/mobile/locales/en/messages.po
  apps/mobile/locales/en/messages.ts
  apps/mobile/locales/vi/messages.po
  apps/mobile/locales/vi/messages.ts
  apps/mobile/package.json
  apps/mobile/stores/user-settings/store.ts
  pnpm-lock.yaml
Labels: enhancement, frontend

#238 feat(mobile): add seed transactions menu
  apps/mobile/app/(app)/(tabs)/settings.tsx
  apps/mobile/hooks/use-seed.tsx
Labels: enhancement, frontend

#239 fix(api): calculate wallet balance from transaction amountInVnd
  apps/api/v1/services/wallet.service.ts
Labels: enhancement, backend

#240 feat(mobile): add statistic view and filter transactions by period
  apps/mobile/app/(app)/(tabs)/index.tsx
  apps/mobile/components/budget/period-control.tsx
  apps/mobile/components/home/header.tsx
  apps/mobile/components/home/select-filter.tsx
  apps/mobile/components/home/time-range-control.tsx
  apps/mobile/components/home/wallet-statistics.tsx
  apps/mobile/components/ui/select.tsx
  apps/mobile/lib/date.tsx
  apps/mobile/locales/en/messages.po
  apps/mobile/locales/en/messages.ts
  apps/mobile/locales/vi/messages.po
  apps/mobile/locales/vi/messages.ts
  apps/mobile/stores/transaction/hooks.tsx
Labels: enhancement, frontend

#241 feat(mobile): add category chart and filter by category
  apps/mobile/app/(app)/(tabs)/index.tsx
  apps/mobile/components/budget/budget-statistic.tsx
  apps/mobile/components/home/category-chart.tsx
  apps/mobile/components/home/wallet-statistics.tsx
  apps/mobile/locales/en/messages.po
  apps/mobile/locales/vi/messages.po
  apps/mobile/stores/transaction/hooks.tsx
Labels: enhancement, frontend

#242 feat(api): cascading user relations
  apps/api/prisma/migrations/20240822091654_cascade_user_relations/migration.sql
  apps/api/prisma/schema.prisma
Labels: enhancement, backend

#243 feat(mobile): correct budget statistic amount
  apps/mobile/app/(app)/(tabs)/budgets.tsx
  apps/mobile/app/(app)/budget/[budgetId]/index.tsx
  apps/mobile/components/budget/budget-item.tsx
  apps/mobile/components/budget/budget-statistic.tsx
  apps/mobile/components/budget/burndown-chart.tsx
  apps/mobile/components/common/circular-progress.tsx
  apps/mobile/stores/budget/hooks.tsx
Labels: enhancement, frontend

#223 feat(mobile): optimize bottom sheet to prevent re-trigger
  apps/mobile/components/category/select-category-icon-field.tsx
  apps/mobile/components/common/bottom-sheet.tsx
  apps/mobile/components/common/date-picker.tsx
  apps/mobile/components/common/date-range-picker.tsx
  apps/mobile/components/form-fields/currency-field.tsx
  apps/mobile/components/setting/select-default-currency.tsx
  apps/mobile/components/transaction/select-account-field.tsx
  apps/mobile/components/transaction/select-category-field.tsx
  apps/mobile/components/wallet/select-account-icon-field.tsx
Labels: enhancement, frontend
